# Generated by Django 3.2 on 2023-04-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainIris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepallength', models.FloatField()),
                ('sepalwidth', models.FloatField()),
                ('label', models.IntegerField(default=1)),
            ],
        ),
    ]
