# Generated by Django 3.2 on 2023-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_testiris'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapleyInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shapley', models.FloatField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
