# Generated by Django 3.2 on 2023-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_shapleyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.FloatField()),
                ('pri', models.FloatField()),
            ],
        ),
    ]
