# Generated by Django 3.2 on 2023-04-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_surveyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=256)),
                ('coverage', models.FloatField()),
                ('price', models.FloatField()),
                ('epsilon', models.FloatField()),
                ('state', models.IntegerField()),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
