# Generated by Django 3.2 on 2023-05-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_modelinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrisHistoryInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('submmitdate', models.DateField(auto_now=True)),
                ('compensation', models.FloatField(null=True)),
            ],
        ),
    ]
